# second.test:
#   path: /second-test/{age<\d+>?1}
#   controller: App\Controller\TestController::secondTest
#   methods: [GET]
#   host: 127.0.0.1
#   schemes: [http, https]
#   #   age: 1
  # requirements:
  #   age: \d+

autowiring.message.test:
  path: '/autowiring/message/{id}'
  controller: App\Controller\TestController::autowiringMessageTest
