# second.test:
#   path: /second-test/{age<\d+>?1}
#   controller: App\Controller\TestController::secondTest
#   methods: [GET]
#   host: 127.0.0.1
#   schemes: [http, https]
#   #   age: 1
  # requirements:
  #   age: \d+

autowiring_message_test:
  path: '/autowiring/{id}/message'
  methods: [GET, PUT]
  defaults:
    _controller: App\Controller\TestController::autowiringMessageTest
